[package]
name = "wikicode"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.12", features = ["macros"] }
regex = "1.11"
once_cell = "1.21"
paste = "1.0.15"
html-escape = "0.2.13"
either = "1.15.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
